using System.Text.Json;
using ZiapStudio.Core.Documents;
using ZiapStudio.Core.Fusion.Audio;
using ZiapStudio.Core.Models;
using ZiapStudio.Core.Preflight;
using ZiapStudio.Services;
using ZiapStudio.Services.Editing;
using ZiapStudio.Services.Fusion.Audio;
using ZiapStudio.Services.Fusion.Preflight.Audio;
using ZiapStudio.Services.Integrations;
using ZiapStudio.Services.Providers;

namespace ZiapStudio.Services.Tests;

public sealed class FusionAudioIntegrationTests
{
    [Fact]
    public async Task PluginRegistry_DetectsActiveNestedFusionAudioWithoutParsingPluginSource()
    {
        using var workspace = new TestWorkspace();
        workspace.WriteFile(
            "js/plugins.js",
            """
            // Generated by RPG Maker.
            var $plugins =
            [
              {"name":"zenkaiDevPlugins/ZDP_FusionAudio","status":true,"description":"Audio","parameters":{}},
              {"name":"Other","status":false,"description":"","parameters":{}}
            ];
            """);
        workspace.WriteFile(
            "js/plugins/zenkaiDevPlugins/ZDP_FusionAudio.js",
            "throw new Error('Studio must not parse or execute this file');");
        var registry = new RpgMakerPluginRegistryService(new FileSystemService());

        var plugins = await registry.LoadAsync(CreateProject(workspace.RootPath));

        Assert.True(await registry.IsActiveAsync(
            CreateProject(workspace.RootPath),
            "ZDP_FusionAudio"));
        Assert.Contains(plugins, plugin =>
            plugin.IsActive && plugin.Name == "zenkaiDevPlugins/ZDP_FusionAudio");
    }

    [Fact]
    public async Task ProjectIntegration_AddsFusionAudioDocumentOnlyWhenPluginIsActive()
    {
        using var workspace = new TestWorkspace();
        workspace.WriteFile("data/System.json", "{\"sounds\":[]}");
        workspace.WriteFile("js/plugins/placeholder.js");
        workspace.WriteFile(
            "js/plugins.js",
            "var $plugins = [{\"name\":\"zenkaiDevPlugins/ZDP_FusionAudio\",\"status\":true,\"parameters\":{}}];");
        var service = new ProjectProviderService(new FileSystemService());

        var roots = await service.BuildExplorerAsync(CreateProject(workspace.RootPath));

        var documentNode = roots.Single(node => node.Name == "System")
            .Children.Single(node => node.Name == "Plugin")
            .Children.Single(node => node.Name == "Fusion Audio");
        Assert.Equal(ProjectExplorerNodeKind.Integration, documentNode.Kind);
        Assert.Equal(DocumentKind.ProjectIntegration, documentNode.Document!.Kind);
        Assert.Equal("fusionaudio://catalog/", documentNode.Document.ResourceId.AbsoluteUri);
    }

    [Fact]
    public async Task CatalogService_ResolvesSystemAndFileSourcesAndReportsMissingAssets()
    {
        using var workspace = new TestWorkspace();
        WriteActivePluginRegistry(workspace);
        workspace.WriteFile(
            "data/System.json",
            """
            {"sounds":[{"name":"ui/Cursor","volume":90,"pitch":100,"pan":0}]}
            """);
        workspace.WriteFile(
            "data/fusion/audio.json",
            """
            {
              "schemaVersion":1,
              "masterVolume":1,
              "categories":{"ui":{"volume":1}},
              "sounds":{
                "ui.navigate":{"category":"ui","source":{"kind":"systemSound","slot":"cursor"},"volume":45,"pitch":{"min":97,"max":103},"pan":0,"cooldown":25,"antiRepeat":false},
                "ui.open":{"category":"ui","source":{"kind":"files","files":["ui/Open","ui/Missing"]},"volume":50,"pitch":{"min":100,"max":100},"pan":0,"cooldown":0,"antiRepeat":true}
              }
            }
            """);
        workspace.WriteFile("audio/se/ui/Cursor.ogg");
        workspace.WriteFile("audio/se/ui/Open.ogg");
        var service = CreateCatalogService(new FileSystemService());
        var descriptor = CreateDescriptor();

        var document = await service.LoadAsync(
            CreateProject(workspace.RootPath),
            descriptor);

        Assert.True(document.PluginIsActive);
        Assert.Equal(2, document.EventCount);
        Assert.Equal(2, document.AssetCount);
        Assert.Contains(document.Assets, asset =>
            asset.EventId == "ui.navigate" && asset.SystemSlot == "cursor" && asset.Exists);
        Assert.Contains(document.Diagnostics, diagnostic =>
            diagnostic.Code == "sound.asset-missing" && diagnostic.EventId == "ui.open");
        Assert.False(document.IsValid);
    }

    [Fact]
    public void CatalogService_DiscoversRecursiveAudioFilesAndCollapsesFormatPairs()
    {
        using var workspace = new TestWorkspace();
        workspace.WriteFile("audio/se/Confirm.ogg");
        workspace.WriteFile("audio/se/Confirm.m4a");
        workspace.WriteFile("audio/se/ui/nested/Popup.wav");
        workspace.WriteFile("audio/se/ui/nested/Voice.mp3");
        workspace.WriteFile("audio/se/readme.txt");
        var service = CreateCatalogService(new FileSystemService());

        var files = service.DiscoverAudioFiles(CreateProject(workspace.RootPath));

        Assert.Equal(3, files.Count);
        var confirm = Assert.Single(files, option => option.CatalogPath == "Confirm");
        Assert.EndsWith("Confirm.ogg", confirm.ResolvedPath, StringComparison.OrdinalIgnoreCase);
        Assert.Equal(["OGG", "M4A"], confirm.Formats);
        Assert.Contains(files, option => option.CatalogPath == "ui/nested/Popup");
        Assert.Contains(files, option => option.CatalogPath == "ui/nested/Voice");
        Assert.DoesNotContain(files, option => option.CatalogPath.Contains("readme"));
    }

    [Fact]
    public async Task PlaybackResolver_AppliesVolumePitchAndPanContractToInMemoryCatalog()
    {
        using var workspace = new TestWorkspace();
        workspace.WriteFile("audio/se/ui/Upgrade.ogg");
        var service = CreateCatalogService(new FileSystemService());
        var resolver = new FusionAudioPlaybackResolver(
            service,
            new SequenceAudioRandomSource(),
            new ManualTimeProvider());
        var catalog = new FusionAudioCatalog
        {
            MasterVolume = 0.8,
            Categories = new Dictionary<string, FusionAudioCategory>
            {
                ["inspect"] = new() { Volume = 0.5 },
            },
        };
        var entry = new FusionAudioEntry
        {
            Category = "inspect",
            Source = new FusionAudioSource { Files = ["ui/Upgrade"] },
            Volume = 50,
            Pitch = new FusionAudioPitch { Min = 120, Max = 120 },
            Pan = 25,
        };

        var resolution = await resolver.ResolveAsync(
            CreateProject(workspace.RootPath),
            catalog,
            "inspect.upgrade",
            entry);

        var plan = Assert.IsType<FusionAudioPlaybackPlan>(resolution.Plan);
        Assert.Equal(FusionAudioPlaybackResolutionStatus.Ready, resolution.Status);
        Assert.Equal(0.20, plan.Volume, precision: 5);
        Assert.Equal(120, plan.Pitch);
        Assert.Equal(1.20, plan.PlaybackRate, precision: 5);
        Assert.Equal(0.25, plan.Pan, precision: 5);
        Assert.Equal("ui/Upgrade", plan.VariantId);
        Assert.EndsWith("audio/se/ui/Upgrade.ogg", plan.RelativePath);
    }

    [Fact]
    public async Task PlaybackResolver_RespectsCooldownAndAvoidsImmediateVariantRepeat()
    {
        using var workspace = new TestWorkspace();
        workspace.WriteFile("audio/se/A.ogg");
        workspace.WriteFile("audio/se/B.ogg");
        var clock = new ManualTimeProvider();
        var resolver = new FusionAudioPlaybackResolver(
            CreateCatalogService(new FileSystemService()),
            new SequenceAudioRandomSource(0, 0, 0),
            clock);
        var project = CreateProject(workspace.RootPath);
        var catalog = new FusionAudioCatalog();
        var entry = new FusionAudioEntry
        {
            Category = "inspect",
            Source = new FusionAudioSource { Files = ["A", "B"] },
            Pitch = new FusionAudioPitch { Min = 100, Max = 100 },
            AntiRepeat = true,
            Cooldown = 100,
        };

        var first = await resolver.ResolveAsync(project, catalog, "inspect.upgrade", entry);
        Assert.Equal("A", first.Plan!.VariantId);
        resolver.CommitPlayback(project, first.Plan);

        var suppressed = await resolver.ResolveAsync(project, catalog, "inspect.upgrade", entry);
        Assert.Equal(FusionAudioPlaybackResolutionStatus.Cooldown, suppressed.Status);
        Assert.Equal(100, suppressed.RemainingCooldownMs);

        clock.Advance(TimeSpan.FromMilliseconds(100));
        var second = await resolver.ResolveAsync(project, catalog, "inspect.upgrade", entry);
        Assert.Equal("B", second.Plan!.VariantId);
    }

    [Fact]
    public async Task PlaybackResolver_ResolvesSystemSoundAndRandomPitch()
    {
        using var workspace = new TestWorkspace();
        workspace.WriteFile(
            "data/System.json",
            "{\"sounds\":[{\"name\":\"ui/Cursor\",\"volume\":90,\"pitch\":100,\"pan\":0}]}" );
        workspace.WriteFile("audio/se/ui/Cursor.ogg");
        var resolver = new FusionAudioPlaybackResolver(
            CreateCatalogService(new FileSystemService()),
            new SequenceAudioRandomSource(0.5),
            new ManualTimeProvider());
        var catalog = new FusionAudioCatalog
        {
            Categories = new Dictionary<string, FusionAudioCategory>
            {
                ["ui"] = new() { Volume = 0.8 },
            },
        };
        var entry = new FusionAudioEntry
        {
            Category = "ui",
            Source = new FusionAudioSource
            {
                Kind = FusionAudioSourceKinds.SystemSound,
                Slot = "cursor",
            },
            Volume = 70,
            Pitch = new FusionAudioPitch { Min = 97, Max = 103 },
        };

        var resolution = await resolver.ResolveAsync(
            CreateProject(workspace.RootPath),
            catalog,
            "ui.navigate",
            entry);

        Assert.Equal(0.56, resolution.Plan!.Volume, precision: 5);
        Assert.Equal(100, resolution.Plan.Pitch);
        Assert.Equal(1, resolution.Plan.PlaybackRate, precision: 5);
        Assert.EndsWith("audio/se/ui/Cursor.ogg", resolution.Plan.RelativePath);
    }

    [Fact]
    public async Task CatalogService_SavesValidCatalogAtomicallyAndProtectsExternalChanges()
    {
        using var workspace = new TestWorkspace();
        WriteActivePluginRegistry(workspace);
        workspace.WriteFile(
            "data/System.json",
            "{\"sounds\":[{\"name\":\"Cursor\",\"volume\":90,\"pitch\":100,\"pan\":0}]}");
        workspace.WriteFile("audio/se/Cursor.ogg");
        workspace.WriteFile(
            "data/fusion/audio.json",
            "{\"schemaVersion\":1,\"masterVolume\":1,\"categories\":{\"ui\":{\"volume\":1}},\"sounds\":{}}");
        var fileSystem = new FileSystemService();
        var service = CreateCatalogService(fileSystem);
        var project = CreateProject(workspace.RootPath);
        var loaded = await service.LoadAsync(project, CreateDescriptor());
        var catalog = loaded.Catalog with
        {
            Sounds = new Dictionary<string, FusionAudioEntry>
            {
                ["ui.navigate"] = new()
                {
                    Category = "ui",
                    Source = new FusionAudioSource
                    {
                        Kind = FusionAudioSourceKinds.SystemSound,
                        Slot = "cursor",
                    },
                    Volume = 45,
                    Pitch = new FusionAudioPitch { Min = 97, Max = 103 },
                    Cooldown = 25,
                },
            },
        };

        var snapshot = await service.SaveAsync(project, catalog, loaded.SourceSnapshot);

        Assert.NotEqual(loaded.SourceSnapshot!.ContentHash, snapshot.ContentHash);
        using var json = JsonDocument.Parse(await File.ReadAllBytesAsync(snapshot.SourcePath));
        Assert.True(json.RootElement.GetProperty("sounds").TryGetProperty("ui.navigate", out _));

        await File.AppendAllTextAsync(snapshot.SourcePath, " ");
        await Assert.ThrowsAsync<ExternalDocumentModificationException>(() =>
            service.SaveAsync(project, catalog with { MasterVolume = 0.9 }, snapshot));
    }

    [Fact]
    public async Task Preflight_MapsFusionAudioDiagnosticsToNavigableIssues()
    {
        using var workspace = new TestWorkspace();
        WriteActivePluginRegistry(workspace);
        workspace.WriteFile("data/System.json", "{\"sounds\":[]}");
        workspace.WriteFile(
            "data/fusion/audio.json",
            "{\"schemaVersion\":1,\"sounds\":{\"ui.confirm\":{\"source\":{\"kind\":\"files\",\"files\":[\"ui/Missing\"]},\"volume\":50,\"pitch\":{\"min\":100,\"max\":100},\"pan\":0,\"cooldown\":0}}}");
        var fileSystem = new FileSystemService();
        var registry = new RpgMakerPluginRegistryService(fileSystem);
        var catalog = new FusionAudioCatalogService(
            fileSystem,
            registry,
            new AtomicJsonFileWriter(fileSystem));
        var provider = new FusionAudioPreflightProvider(catalog, registry);

        var issues = await provider.ScanAsync(CreateProject(workspace.RootPath));

        var issue = Assert.Single(issues, issue => issue.RuleId == "fusion-audio.sound.asset-missing");
        Assert.Equal("FusionAudio", issue.Scope);
        Assert.Equal("ui.confirm", issue.RecordName);
        Assert.Equal("fusionaudio://catalog/event/ui.confirm", issue.NavigationTarget!.AbsoluteUri);
        Assert.Equal(PreflightSeverity.Error, issue.Severity);
    }

    private static FusionAudioCatalogService CreateCatalogService(FileSystemService fileSystem)
    {
        var registry = new RpgMakerPluginRegistryService(fileSystem);
        return new FusionAudioCatalogService(
            fileSystem,
            registry,
            new AtomicJsonFileWriter(fileSystem));
    }

    private static DocumentDescriptor CreateDescriptor() => new()
    {
        Id = new DocumentId("test:integration:fusion-audio"),
        DisplayName = "Fusion Audio",
        Kind = DocumentKind.ProjectIntegration,
        ResourceId = new Uri("fusionaudio://catalog/"),
    };

    private static void WriteActivePluginRegistry(TestWorkspace workspace) =>
        workspace.WriteFile(
            "js/plugins.js",
            "var $plugins = [{\"name\":\"zenkaiDevPlugins/ZDP_FusionAudio\",\"status\":true,\"parameters\":{}}];");

    private static ZiapProject CreateProject(string path) => new()
    {
        Id = "test",
        Name = "Test",
        ProjectType = KnownProjectTypes.RpgMakerMz,
        Path = path,
        IsZiapInitialized = true,
    };

    private sealed class SequenceAudioRandomSource(params double[] values)
        : IFusionAudioRandomSource
    {
        private readonly Queue<double> _values = new(values);

        public double NextDouble() => _values.Count > 0 ? _values.Dequeue() : 0;
    }

    private sealed class ManualTimeProvider : TimeProvider
    {
        private DateTimeOffset _utcNow = new(2026, 8, 19, 12, 0, 0, TimeSpan.Zero);

        public override DateTimeOffset GetUtcNow() => _utcNow;

        public void Advance(TimeSpan duration) => _utcNow += duration;
    }
}
